import axios from "../axios";

const endpoints = {
    activateAccount: (token) => axios.get(`/auth/activate/${token}`),
    registration: (data) => axios.post("/users", data),
    refresh: (data) => axios.post('/auth/refresh', data),
    login: (data) => axios.post("/auth", data),
    // forgotPassword: (data) => axios.post("/v1/auth/forgot/password", data),
    // getApartments: (page) => axios.get(`/apartments?page=${page}`),
    // updateProfile: (data) => axios.patch("/v1/auth/me", data),
    getApartment: (id) => axios.get(`/apartments/${id}`),
    getUsers: (page) => axios.get(`/users?page=${page}`),
    getUser: (id) => axios.get(`/users/${id}`),
    getCommentsApartment: () => axios.get('/comments_apartment'),
    getUserBlocked: (id) => axios.put(`/users/${id}/blocked`),
    getUserActivate: (id) => axios.patch(`/users/${id}/blocked`),
    getCommentsUsers: (page) => axios.get(`/comments_user?page=${page}`),
    getCommentsApartments: (page) => axios.get(`/comments_apartment?page=${page}`),
    getCommentApartments: (id) => axios.get(`/comments_apartment/${id}`),
    getCommentUsers: (id) => axios.get(`/comments_user/${id}`),
    deleteCommentApartment: (id) => axios.delete(`/comments_apartment/${id}`),
    deleteCommentUser: (id) => axios.delete(`/comments_user/${id}`),
    changeCommentApartment: (id, obj) => axios.patch(`/comments_apartment/${id}`, obj),
    changeCommentUser: (id, obj) => axios.patch(`/comments_user/${id}`, obj),
    changeApartment: (id, obj) => axios.patch(`/apartments/${id}`, obj),
    deleteApartment: (id) => axios.delete(`/apartments/${id}`),
    addApartment: (obj) => axios.post('/apartments', obj),
    changeAllApartment: (id, obj) => axios.put(`/apartments/${id}`, obj),
    changeUserNoManager: (id) => axios.put(`/users/${id}/manager`),
    changeUserManager: (id) => axios.patch(`/users/${id}/manager`),
    sendCommentsApartment: (id, obj) => axios.post(`/apartments/${id}/comment_apartment`, obj),
    rentApartment: (id, obj) => axios.post(`/apartments/${id}/selected_date`, obj),
    addPhotoRooms: (id, formData) => axios.patch(`/apartments/${id}/photo_rooms`, formData),
    getDateSelection: () => axios.get('/date_selection'),
    sendCommentUser: (id, obj) => axios.post(`/users/${id}/comment_user`, obj),
    addPhotoCommentApartment: (id, formData) => axios.patch(`/comments_apartment/${id}/addPhoto`, formData),
    addPhotoCommentUser: (id, obj) => axios.patch(`/comments_user/${id}/addPhoto`, obj),
    deleteApartmentPhotoRooms: (id) => axios.delete(`/apartments/photo_rooms/${id}`),
    deletePhotoCommentApartment: (id) => axios.delete(`/comments_apartment/deletePhoto/${id}`),
    deletePhotoCommentUser: (id) => axios.delete(`/comments_user/deletePhoto/${id}`),
    activateYes: (token) => axios.get(`/date_selection/yes/${token}`),
    activateNo: (token) => axios.get(`/date_selection/no/${token}`),
};

export default endpoints;